[package]
name = "grepr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0" # Error type
clap = { version = "4.3.0", features = ["derive"] } # CLI Parser

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"
assert_fs = "1.0"